from . import document_type
from . import onboarding_template
from . import onboarding_request
from . import onboarding_request_line
from . import onboarding_document
from . import onboarding_value
from . import onboarding_fill_line
from . import hr_applicant
from . import hr_employee
from . import res_config_settings
from . import mail_mail
