{
    "name": "ninthsense",
    "version": "20.0.1.0.0",
    "category": "Human Resources/Recruitment",
    "summary": "Collect a hired applicant's documents through 9thSense and fill the new employee",
    "author": "Digio Labs",
    "license": "LGPL-3",
    "application": False,
    "depends": ["hr", "hr_recruitment", "hr_skills"],
    "external_dependencies": {"python": ["jsonschema"]},
    "post_load": "post_load",
    "uninstall_hook": "uninstall_hook",
    "data": [
        "security/ir.access.csv",
        "security/security_rules.xml",
        "data/ir_sequence_data.xml",
        "data/document_type_data.xml",
        "data/template_data.xml",
        "data/mail_template_data.xml",
        "views/onboarding_request_views.xml",
        "views/hr_applicant_views.xml",
        "views/res_config_settings_views.xml",
        "views/onboarding_template_views.xml",
        "wizard/send_wizard_views.xml",
        "wizard/link_dialog_views.xml",
    ],
    "assets": {
        "web.assets_tests": ["ninthsense/static/tests/tours/*.js"],
    },
}
