from . import test_models
from . import test_source_scans
from . import test_send
from . import test_applicant_button
from . import test_invite_state
from . import test_tours
from . import test_portal_api
from . import test_delivery_flow
from . import test_create_employee
from . import test_employee_save
from . import test_cancel
from . import test_settings
from . import test_template
from . import test_data_reload
from . import test_no_full_aadhaar
from . import test_access
from . import test_multi_company
from . import test_log_privacy
from . import test_install
